name: Flutter Android APK (Full)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      # Сначала создаём проект и копируем наши файлы,
      # чтобы появились android/* и gradle-файлы
      - name: Create Flutter scaffold and copy sources
        run: |
          flutter --version
          flutter create . --project-name workgrid
          # Переносим наши исходники из src/ поверх сгенерированных
          cp -v src/pubspec.yaml pubspec.yaml
          mkdir -p lib
          cp -vr src/lib/* lib/

      # Теперь gradle-файлы уже есть → можно настраивать Java с кешем Gradle
      - name: Set up Java (with Gradle cache)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Get packages
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
