name: Flutter Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Flutter scaffold
        run: |
          flutter --version
          flutter create . --project-name workgrid_flutter
          rm -f lib/main.dart
          rm -f pubspec.yaml
          cp -v repo/lib/main.dart lib/main.dart
          cp -v repo/pubspec.yaml pubspec.yaml

      - name: Get packages
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
